(ns re-complete.autocomplete-data)

(def vegetables '("Amaranth"
                  "Arrowroot"
                  "Banana Squash"
                  "Bell Peppers"
                  "Black Eyed Peas"
                  "Black Radish"
                  "Bok Choy"
                  "Broccoflower"
                  "Broccolini"
                  "Burdock Root"
                  "Cabbage"
                  "Carrots"
                  "Celeriac (Celery Root)"
                  "Celery"
                  "Cherry Tomatoes"
                  "Chinese Eggplants"
                  "Galangal Root"
                  "Leek"
                  "Lettuce"
                  "Mushrooms"
                  "Olives"
                  "Onions"
                  "Parsnips"
                  "Pearl Onions"
                  "Potatoes"
                  "Rutabagas"
                  "Salad Savoy"
                  "Snow Peas"
                  "Wasabi Root"
                  "Yucca Root"
                  "Artichokes"
                  "Asparagus"
                  "Belgian Endive"
                  "Broccoli"
                  "Butter Lettuce"
                  "Cactus"
                  "Chayote Squash"
                  "Chives"
                  "Collard Greens"
                  "Corn"
                  "Fava Beans"
                  "Fennel"
                  "Fiddlehead Ferns"
                  "Green Beans"
                  "Manoa Lettuce"
                  "Morel Mushrooms"
                  "Mustard Greens"
                  "Pea Pods"
                  "Peas"
                  "Purple Asparagus"
                  "Radicchio"
                  "Ramps"
                  "Red Leaf Lettuce"
                  "Rhubarb"
                  "Snow Peas"
                  "Sorrel"
                  "Spinach"
                  "Spring Baby Lettuce"
                  "Swiss Chard"
                  "Vidalia Onions"
                  "Watercress"
                  "Acorn Squash"
                  "Belgian Endive"
                  "Black Salsify"
                  "Broccoli"
                  "Brussels Sprouts"
                  "Butter Lettuce"
                  "Buttercup Squash"
                  "Butternut Squash"
                  "Cauliflower"
                  "Chayote Squash"
                  "Chinese Long Beans"
                  "Delicata Squash"
                  "Diakon Radish"
                  "Endive"
                  "Garlic"
                  "Ginger"
                  "Jalapeno Peppers"
                  "Jerusalem Artichoke"
                  "Kohlrabi"
                  "Pumpkin"
                  "Radicchio"
                  "Sweet Dumpling Squash"
                  "Sweet Potatoes"
                  "Swiss Chard"
                  "Turnips"
                  "Winter Squash"))

(def fruits '("Acai"
              "Aceola"
              "Apple"
              "Apricots"
              "Avocado"
              "Banana"
              "Blackberry"
              "Blueberries"
              "Camu Camu berry"
              "Cherries"
              "Coconut"
              "Cranberry"
              "Cucumber"
              "Currents"
              "Dates"
              "Durian"
              "Fig"
              "Goji berries"
              "Gooseberry"
              "Grapefruit"
              "Grapes"
              "Jackfruit"
              "Kiwi"
              "Kumquat"
              "Lemon"
              "Lime"
              "Lucuma"
              "Lychee"
              "Mango"
              "Mangosteen"
              "Melon"
              "Mulberry"
              "Nectarine"
              "Orange"
              "Papaya"
              "Passion Fruit"
              "Peach"
              "Pear"
              "Pineapple"
              "Plum"
              "Pomegranate"
              "Pomelo"
              "Prickly Pear"
              "Prunes"
              "Raspberries"
              "Strawberries"
              "Tangerine"
              "Clementine"
              "Watermelon"))

(def grains '("Amaranth"
              "Barley"
              "Brown Rice"
              "Brown Rice Bread"
              "Brown Rice Tortilla"
              "Buckwheat"
              "Bulgur (Cracked Wheat)"
              "Farro / Emmer"
              "Flaxseed"
              "Grano"
              "Kamut Grain"
              "Millet"
              "Oats"
              "Oat Bread"
              "Oat Cereal"
              "Oatmeal"
              "Popcorn"
              "Whole Wheat Cereal Flakes"
              "Muesli"
              "Rolled Oats"
              "Quinoa"
              "Rye"
              "Sorghum"
              "Spelt"
              "Teff"
              "Triticale"
              "Whole Grain Barley"
              "Wheat Berries"
              "Whole Grain Cornmeal"
              "Whole Rye"
              "Whole Wheat Bread"
              "Whole Wheat Couscous"
              "Whole Wheat Crackers"
              "Whole Wheat Pasta"
              "Whole Wheat Pita Bread"
              "Whole Wheat Sandwich Buns And Rolls"
              "Whole Wheat Tortillas"
              "Wild Rice"))
